server:
  port: 8088
spring:
  jpa:
    database: oracle
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.Oracle12cDialect
  datasource:
    url: jdbc:oracle:thin:@//172.17.0.2:1521/ORCLPDB1
    password: Simple_rest_123
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: simplerest
logging:
  level:
    org.springframework.web: WARN
    com.epam.shop: DEBUG